// siso-appultimo/functions/api/internal-store/portal-empresa-financiero/[nit].js
// HALLAZGO P0 ACTIVO (ver CLAUDE.md): PortalEmpresaPage.jsx.cargarDocumentos()
// (líneas 145-233, código real commit 6eb4574) descargaba TODO el array de
// siso_saved_bills_${userId} y siso_caja_movs_${userId} — es decir, TODA la
// facturación y movimientos de caja de TODO el consultorio, de TODAS las
// empresas — y filtraba por NIT DESPUÉS, en el navegador. Confirmado en
// HistoriaPage.jsx:551-561: cada registro incluye pacienteNombre, pacienteDoc,
// tipoConsulta, medicoNombre — no son datos financieros puros, son
// PHI-adyacentes de pacientes de TODAS las empresas. Combinado con el bypass
// de codigoAcceso vacío (ver CLAUDE.md), era explotable sin autenticación
// real, visible en el payload de red de cualquier visitante con DevTools.
//
// Este endpoint filtra SERVER-SIDE, antes de construir la respuesta. El
// cliente nunca recibe el array completo bajo ninguna circunstancia.
//
// Mismo gate de codigoAcceso que portal-empresa-nit/portal-empresa-docs
// (_portalEmpresaAuth.js). Método POST, mismo razonamiento (código de
// acceso nunca en query string).
//
// Proyección — SOLO los campos que PortalEmpresaPage.jsx realmente
// renderiza para cuenta/custodia (confirmado leyendo el JSX real, líneas
// ~560-580 y 313-334): concepto, monto, periodo, mesTexto, anio, savedAt,
// empresaNombre. Deliberadamente EXCLUIDOS: pacienteNombre, pacienteDoc,
// pacienteId, medicoId, medicoNombre, tipoConsulta, codigoVerificacion,
// empresaClienteId, empresaClienteNombre, _autoGenerated — ninguno se
// renderiza en esta pantalla, y varios son PHI-adyacentes de pacientes de
// OTRAS empresas que nunca deben llegar al cliente.
//
// El userId server-side sigue siendo el mismo fallback ('drcucalon') que
// ya usa el código real — este endpoint NO corrige ese hardcodeo (ver
// hallazgo relacionado ya documentado sobre useBackendData.js en fases
// anteriores de esta auditoría); solo corrige que el filtrado por NIT
// ocurra en el servidor y no en el cliente. Corregir el userId hardcodeado
// requeriría resolver identidad real de sesión, fuera del alcance de este
// bloque (que es contener la fuga con el modelo de datos actual, no
// rediseñarlo).
//
// Contrato:
//   POST /api/internal-store/portal-empresa-financiero/:nit   body: { codigo }
//   200 { autorizado: true, nit, cuentas: [...], custodia: [...] }
//   404 { error: "No encontrado" }
//   405 { error: "Método no permitido" }
//   502 { error: "Error del servidor" }

import { isValidNitFormat, validateAccessCode } from "../_portalEmpresaAuth.js";

const MAX_REGISTROS = 30; // mismo tope que el código real (.slice(0, 30))

function projectFinancialFields(raw, empresaNombre) {
  if (!raw || typeof raw !== "object") return null;
  return {
    concepto: typeof raw.concepto === "string" ? raw.concepto : null,
    monto: typeof raw.monto === "string" || typeof raw.monto === "number" ? raw.monto : null,
    periodo: typeof raw.periodo === "string" ? raw.periodo : null,
    fecha: typeof raw.fecha === "string" ? raw.fecha : null,
    mesTexto: typeof raw.mesTexto === "string" ? raw.mesTexto : null,
    anio: typeof raw.anio === "string" || typeof raw.anio === "number" ? raw.anio : null,
    savedAt: typeof raw.savedAt === "string" ? raw.savedAt : null,
    empresaNombre: typeof empresaNombre === "string" ? empresaNombre : null,
  };
}

async function fetchFromWorker(env, key) {
  const workerUrl = env.WORKER_URL || "https://siso-api.dr-juliancucalon.workers.dev";
  const res = await fetch(`${workerUrl}/store/${encodeURIComponent(key)}`, {
    headers: { "X-Siso-Token": env.SISO_TOKEN || "" },
  });
  if (!res.ok) throw new Error(`worker_status_${res.status}`);
  const rows = await res.json();
  return Array.isArray(rows) && rows.length > 0 ? rows[0].value : null;
}

function jsonResponse(status, body) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

// userId server-side — mismo fallback que el código real, mismo hardcodeo
// conocido (ver comentario arriba). No recibido nunca del cliente.
function resolveUserId() {
  return "drcucalon";
}

export async function onRequestPost(context) {
  const { params, env, request } = context;
  const nitRaw = params?.nit;

  if (!isValidNitFormat(nitRaw)) {
    return jsonResponse(404, { error: "No encontrado" });
  }
  if (!env?.SISO_TOKEN) {
    return jsonResponse(502, { error: "Error del servidor" });
  }

  let body;
  try {
    body = await request.json();
  } catch {
    return jsonResponse(404, { error: "No encontrado" });
  }
  const codigo = typeof body?.codigo === "string" ? body.codigo : "";

  try {
    const { authorized, docsRecord, matchedNit } = await validateAccessCode(env, nitRaw, codigo);
    if (!authorized) {
      return jsonResponse(404, { error: "No encontrado" });
    }

    const nitClean = String(nitRaw).replace(/\D/g, "");
    const empresaNombre = typeof docsRecord?.nombre === "string" ? docsRecord.nombre : null;
    const userId = resolveUserId();

    const [billsRaw, cajaRaw, custRaw] = await Promise.all([
      fetchFromWorker(env, `siso_saved_bills_${userId}`).catch(() => null),
      fetchFromWorker(env, `siso_caja_movs_${userId}`).catch(() => null),
      fetchFromWorker(env, `siso_cartas_custodia_${userId}`).catch(() => null),
    ]);

    // ── FILTRADO SERVER-SIDE — el array completo NUNCA sale de aquí ──
    const todasCuentas = [...(Array.isArray(billsRaw) ? billsRaw : []), ...(Array.isArray(cajaRaw) ? cajaRaw : [])];
    const cuentasFiltradas = todasCuentas.filter((m) => {
      const idMatch = String(m?.empresaClienteId || "").replace(/\D/g, "") === nitClean;
      const nombreMatch = String(m?.empresaClienteNombre || "").toLowerCase().includes(nitClean);
      return idMatch || (!idMatch && nombreMatch);
    }).slice(0, MAX_REGISTROS);

    const custodiaFiltrada = (Array.isArray(custRaw) ? custRaw : []).filter((c) => {
      const nitC = String(c?.empresaNit || c?.nit || "").replace(/\D/g, "");
      return nitC === nitClean || nitC.includes(nitClean) || nitClean.includes(nitC);
    }).slice(0, MAX_REGISTROS);

    const cuentas = cuentasFiltradas.map((c) => projectFinancialFields(c, empresaNombre)).filter(Boolean);
    const custodia = custodiaFiltrada.map((c) => projectFinancialFields(c, empresaNombre)).filter(Boolean);

    return jsonResponse(200, { autorizado: true, nit: matchedNit || nitClean, cuentas, custodia });
  } catch (e) {
    return jsonResponse(502, { error: "Error del servidor" });
  }
}
